version: "3.7"

services:
    server:
        image: tyke_test

    mongo:
        image: mongo

    test:
        image: tyke_test
        depends_on:
            - server
        command: sh -c "sleep 5 && npm run test:full"
        environment:
            - TEST_API_URL=http://server:3000
